### ISSUE TITLE
Bug: App doesn't start

### ISSUE THREAD

**Issue by isgj** [mattermost/focalboard#4104]
## Steps to reproduce the behavior

1. Launch the app

## Expected behavior

The app should start and run

## Screenshots (optional)

[Screencast from 29-10-22 16:08:34.webm](https://user-images.githubusercontent.com/20517048/198836124-441734d1-fdc7-46e5-8ef1-883291883be8.webm)

## Edition and Platform

 - Edition: Personal Desktop
 - Version: v7.4.3
 - Browser and OS: Ubuntu 22.04

## Additional context (optional)

<details>
<summary>Error stack</summary>

```
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7f53da4e13bb]

runtime stack:
runtime.throw({0x136a0ea?, 0x7f53dc451c5f?})
	/opt/hostedtoolcache/go/1.18.1/x64/src/runtime/panic.go:992 +0x71
runtime.sigpanic()
	/opt/hostedtoolcache/go/1.18.1/x64/src/runtime/signal_unix.go:802 +0x3a9

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x104a930, 0xc000d1fe90)
	/opt/hostedtoolcache/go/1.18.1/x64/src/runtime/cgocall.go:157 +0x5c fp=0xc000d1fe68 sp=0xc000d1fe30 pc=0x41581c
github.com/webview/webview._Cfunc_webview_run(0x2834d90)
	_cgo_gotypes.go:232 +0x45 fp=0xc000d1fe90 sp=0xc000d1fe68 pc=0x1047105
github.com/webview/webview.(*webview).Run.func1(0xc000c4c4e0?)
	/home/runner/go/pkg/mod/github.com/webview/webview@v0.0.0-20220314230258-a2b7746141c3/webview.go:171 +0x3a fp=0xc000d1fec8 sp=0xc000d1fe90 pc=0x10476ba
github.com/webview/webview.(*webview).Run(0x132eb62?)
	/home/runner/go/pkg/mod/github.com/webview/webview@v0.0.0-20220314230258-a2b7746141c3/webview.go:171 +0x19 fp=0xc000d1fee0 sp=0xc000d1fec8 pc=0x1047659
main.main()
	/home/runner/work/focalboard/focalboard/linux/main.go:146 +0x2de fp=0xc000d1ff80 sp=0xc000d1fee0 pc=0x104a31e
runtime.main()
	/opt/hostedtoolcache/go/1.18.1/x64/src/runtime/proc.go:250 +0x212 fp=0xc000d1ffe0 sp=0xc000d1ff80 pc=0x44b7f2
runtime.goexit()
	/opt/hostedtoolcache/go/1.18.1/x64/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000d1ffe8 sp=0xc000d1ffe0 pc=0x478ac1

goroutine 277 [select]:
github.com/mattermost/focalboard/server/utils.(*CallbackQueue).loop(0xc00009de50, 0xc0001d3440?)
	/home/runner/work/focalboard/focalboard/server/utils/callbackqueue.go:110 +0xe5
created by github.com/mattermost/focalboard/server/utils.NewCallbackQueue
	/home/runner/work/focalboard/focalboard/server/utils/callbackqueue.go:44 +0x147

goroutine 10 [select]:
github.com/mattermost/logr/v2.(*Logr).start(0xc0000e38c0)
	/home/runner/go/pkg/mod/github.com/mattermost/logr/v2@v2.0.15/logr.go:404 +0xc5
created by github.com/mattermost/logr/v2.New
	/home/runner/go/pkg/mod/github.com/mattermost/logr/v2@v2.0.15/logr.go:80 +0x3a5

goroutine 11 [select]:
database/sql.(*DB).connectionOpener(0xc000692dd0, {0x1560590, 0xc000330800})
	/opt/hostedtoolcache/go/1.18.1/x64/src/database/sql/sql.go:1226 +0x8d
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.18.1/x64/src/database/sql/sql.go:794 +0x18d

goroutine 276 [select]:
github.com/mattermost/focalboard/server/utils.(*CallbackQueue).loop(0xc00009de50, 0xc0001d34d0?)
	/home/runner/work/focalboard/focalboard/server/utils/callbackqueue.go:110 +0xe5
created by github.com/mattermost/focalboard/server/utils.NewCallbackQueue
	/home/runner/work/focalboard/focalboard/server/utils/callbackqueue.go:44 +0x147

goroutine 278 [select]:
github.com/mattermost/focalboard/server/utils.(*CallbackQueue).loop(0xc00009de50, 0xc0004fe000?)
	/home/runner/work/focalboard/focalboard/server/utils/callbackqueue.go:110 +0xe5
created by github.com/mattermost/focalboard/server/utils.NewCallbackQueue
	/home/runner/work/focalboard/focalboard/server/utils/callbackqueue.go:44 +0x147

goroutine 275 [select]:
github.com/mattermost/focalboard/server/utils.(*CallbackQueue).loop(0xc00009de50, 0xc0004fe090?)
	/home/runner/work/focalboard/focalboard/server/utils/callbackqueue.go:110 +0xe5
created by github.com/mattermost/focalboard/server/utils.NewCallbackQueue
	/home/runner/work/focalboard/focalboard/server/utils/callbackqueue.go:44 +0x147

goroutine 274 [select]:
github.com/mattermost/focalboard/server/utils.(*CallbackQueue).loop(0xc00009de50, 0xc0004fe240?)
	/home/runner/work/focalboard/focalboard/server/utils/callbackqueue.go:110 +0xe5
created by github.com/mattermost/focalboard/server/utils.NewCallbackQueue
	/home/runner/work/focalboard/focalboard/server/utils/callbackqueue.go:44 +0x147

goroutine 271 [select]:
github.com/mattermost/focalboard/server/utils.(*CallbackQueue).loop(0xc00009de50, 0x0?)
	/home/runner/work/focalboard/focalboard/server/utils/callbackqueue.go:110 +0xe5
created by github.com/mattermost/focalboard/server/utils.NewCallbackQueue
	/home/runner/work/focalboard/focalboard/server/utils/callbackqueue.go:44 +0x147

goroutine 273 [select]:
github.com/mattermost/focalboard/server/utils.(*CallbackQueue).loop(0xc00009de50, 0xc0005da090?)
	/home/runner/work/focalboard/focalboard/server/utils/callbackqueue.go:110 +0xe5
created by github.com/mattermost/focalboard/server/utils.NewCallbackQueue
	/home/runner/work/focalboard/focalboard/server/utils/callbackqueue.go:44 +0x147

goroutine 272 [select]:
github.com/mattermost/focalboard/server/utils.(*CallbackQueue).loop(0xc00009de50, 0xc0001d3d40?)
	/home/runner/work/focalboard/focalboard/server/utils/callbackqueue.go:110 +0xe5
created by github.com/mattermost/focalboard/server/utils.NewCallbackQueue
	/home/runner/work/focalboard/focalboard/server/utils/callbackqueue.go:44 +0x147

goroutine 270 [select]:
github.com/mattermost/logr/v2.(*Logr).start(0xc0005ca0b0)
	/home/runner/go/pkg/mod/github.com/mattermost/logr/v2@v2.0.15/logr.go:404 +0xc5
created by github.com/mattermost/logr/v2.New
	/home/runner/go/pkg/mod/github.com/mattermost/logr/v2@v2.0.15/logr.go:80 +0x3a5

goroutine 224 [chan receive]:
github.com/rudderlabs/analytics-go.(*executor).loop(0xc0001768e0)
	/home/runner/go/pkg/mod/github.com/rudderlabs/analytics-go@v3.3.2+incompatible/executor.go:39 +0x47
created by github.com/rudderlabs/analytics-go.newExecutor
	/home/runner/go/pkg/mod/github.com/rudderlabs/analytics-go@v3.3.2+incompatible/executor.go:17 +0xaa

goroutine 279 [select]:
github.com/mattermost/focalboard/server/utils.(*CallbackQueue).loop(0xc00009de50, 0x0?)
	/home/runner/work/focalboard/focalboard/server/utils/callbackqueue.go:110 +0xe5
created by github.com/mattermost/focalboard/server/utils.NewCallbackQueue
	/home/runner/work/focalboard/focalboard/server/utils/callbackqueue.go:44 +0x147

goroutine 280 [select]:
github.com/mattermost/focalboard/server/utils.(*CallbackQueue).loop(0xc00009de50, 0x0?)
	/home/runner/work/focalboard/focalboard/server/utils/callbackqueue.go:110 +0xe5
created by github.com/mattermost/focalboard/server/utils.NewCallbackQueue
	/home/runner/work/focalboard/focalboard/server/utils/callbackqueue.go:44 +0x147

goroutine 290 [IO wait]:
internal/poll.runtime_pollWait(0x7f53a92a43c0, 0x72)
	/opt/hostedtoolcache/go/1.18.1/x64/src/runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0xc00049ee00?, 0x0?, 0x0)
	/opt/hostedtoolcache/go/1.18.1/x64/src/internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.18.1/x64/src/internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).Accept(0xc00049ee00)
	/opt/hostedtoolcache/go/1.18.1/x64/src/internal/poll/fd_unix.go:614 +0x22c
net.(*netFD).accept(0xc00049ee00)
	/opt/hostedtoolcache/go/1.18.1/x64/src/net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0xc000354270)
	/opt/hostedtoolcache/go/1.18.1/x64/src/net/tcpsock_posix.go:139 +0x28
net.(*TCPListener).Accept(0xc000354270)
	/opt/hostedtoolcache/go/1.18.1/x64/src/net/tcpsock.go:288 +0x3d
net/http.(*Server).Serve(0xc000130f00, {0x155f860, 0xc000354270})
	/opt/hostedtoolcache/go/1.18.1/x64/src/net/http/server.go:3039 +0x385
net/http.(*Server).ListenAndServe(0xc000130f00)
	/opt/hostedtoolcache/go/1.18.1/x64/src/net/http/server.go:2968 +0x7d
github.com/mattermost/focalboard/server/web.(*Server).Start.func2()
	/home/runner/work/focalboard/focalboard/server/web/webserver.go:127 +0x36
created by github.com/mattermost/focalboard/server/web.(*Server).Start
	/home/runner/work/focalboard/focalboard/server/web/webserver.go:126 +0x3ca

goroutine 291 [select]:
github.com/mattermost/focalboard/server/services/scheduler.createTask.func1()
	/home/runner/work/focalboard/focalboard/server/services/scheduler/scheduler.go:47 +0xf7
created by github.com/mattermost/focalboard/server/services/scheduler.createTask
	/home/runner/work/focalboard/focalboard/server/services/scheduler/scheduler.go:40 +0x165

goroutine 292 [select]:
github.com/mattermost/focalboard/server/services/scheduler.createTask.func1()
	/home/runner/work/focalboard/focalboard/server/services/scheduler/scheduler.go:47 +0xf7
created by github.com/mattermost/focalboard/server/services/scheduler.createTask
	/home/runner/work/focalboard/focalboard/server/services/scheduler/scheduler.go:40 +0x165

goroutine 293 [select]:
github.com/rudderlabs/analytics-go.(*client).loop(0xc000dfe000)
	/home/runner/go/pkg/mod/github.com/rudderlabs/analytics-go@v3.3.2+incompatible/analytics.go:512 +0x22d
created by github.com/rudderlabs/analytics-go.NewWithConfig
	/home/runner/go/pkg/mod/github.com/rudderlabs/analytics-go@v3.3.2+incompatible/analytics.go:99 +0x665

goroutine 144 [select]:
github.com/mattermost/focalboard/server/services/scheduler.createTask.func1()
	/home/runner/work/focalboard/focalboard/server/services/scheduler/scheduler.go:47 +0xf7
created by github.com/mattermost/focalboard/server/services/scheduler.createTask
	/home/runner/work/focalboard/focalboard/server/services/scheduler/scheduler.go:40 +0x165
```

</details>

**Comment by jespino** [comment]
Interesting, I'm not able to reproduce this in my Ubuntu 22.04. @isgj can you check if you have installed the packages `libgtk-3-0 libwebkit2gtk-4.0-37`?

**Comment by isgj** [comment]
Yes I have them installed

![image](https://user-images.githubusercontent.com/20517048/199591605-18105d55-424b-4223-ac53-d0c380bd392f.png)

I'm able to run `focalboard` in another PC:
Intel GPU + wayland --> works
Nvidia + wayland --> doesn't work

**Comment by jespino** [comment]
really weird, I'm on nvidia + x11 and is working fine. I guess is some kind of problem with webview (the library that we use to embed webapp in a desktop app). I'll need to try to reproduce that locally with nvidia+wayland

**Comment by jespino** [comment]
@mgdelacroix I think you can take a look to this.
