### ISSUE TITLE
Bug: import from trello

### ISSUE THREAD

**Issue by lexoyo** [mattermost/focalboard#4532]
## Steps to reproduce the behavior

1. follow the steps from the docs: https://docs.mattermost.com/boards/migrate-to-boards.html#import-from-trello
1. error: 

```sh
$ npx ts-node importTrello.ts -i ~/Downloads/trello-i2k.json -o ./archive.boardarchive              

/home/lexoyo/Documents/tests/focalboard/import/trello/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
../../webapp/src/blocks/board.ts:4:24 - error TS2307: Cannot find module 'lodash/difference' or its corresponding type declarations.

4 import difference from 'lodash/difference'
                         ~~~~~~~~~~~~~~~~~~~

    at createTSError (/home/lexoyo/Documents/tests/focalboard/import/trello/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/home/lexoyo/Documents/tests/focalboard/import/trello/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/home/lexoyo/Documents/tests/focalboard/import/trello/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/home/lexoyo/Documents/tests/focalboard/import/trello/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/home/lexoyo/Documents/tests/focalboard/import/trello/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Object.require.extensions.<computed> [as .ts] (/home/lexoyo/Documents/tests/focalboard/import/trello/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Function.Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
```

## Expected behavior

Create ./archive.boardarchive

## Edition and Platform

 - Edition: Main branch of focalboard, local fedora
 - Version: git hash 08ce9a753d77eca18ae385ac09dceb246f955254
 - Browser and OS: nodejs v18.13.0 (tried also v16.13.1) on fedora

## Additional context (optional)

I tried with a trello board I just created now and it does the same as with a non-empty/old board

Here is the json: 
[trello-test.zip](https://github.com/mattermost/focalboard/files/10545890/trello-test.zip)

**Comment by sbishel** [comment]
@lexoyo Any errors when you run - `npm install`? You may want to clear `node_modules` and try again. A dependent library isn't being installed. I'm running node `v16.4.0`, but not fedora.

**Comment by lexoyo** [comment]
hey @sbishel thank you so much for the answer

I tried this but unfortunately it didn't work:

```sh
12:31PM [main] node -v
v16.13.1
12:31PM [main] import/trello $ rm -rf package-lock.json node_modules && npm i

added 164 packages, and audited 165 packages in 14s

28 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
12:31PM [main] import/trello $ npx ts-node importTrello.ts -i ~/Downloads/trello-test.json -o ./archive.boardarchive

/home/lexoyo/Documents/tests/focalboard/import/trello/node_modules/ts-node/src/index.ts:513
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
../../webapp/src/blocks/board.ts:4:24 - error TS2307: Cannot find module 'lodash/difference' or its corresponding type declarations.

4 import difference from 'lodash/difference'
                         ~~~~~~~~~~~~~~~~~~~

    at createTSError (/home/lexoyo/Documents/tests/focalboard/import/trello/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/home/lexoyo/Documents/tests/focalboard/import/trello/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/home/lexoyo/Documents/tests/focalboard/import/trello/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/home/lexoyo/Documents/tests/focalboard/import/trello/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/home/lexoyo/Documents/tests/focalboard/import/trello/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/home/lexoyo/Documents/tests/focalboard/import/trello/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

> A dependent library isn't being installed

Are you talking about `lodash/difference` ?

I have these modules: 

```sh
12:32PM [main] l node_modules/lodash 
lodash/           lodash.merge/     lodash.truncate/
```

And in `node_modules/lodash` there is

```sh
12:34PM [main] import/trello $ l node_modules/lodash/difference
differenceBy.js    difference.js      differenceWith.js
```

So `lodash/difference` is looking for `node_modules/lodash/difference.ts` so it is not there

**Comment by lexoyo** [comment]
Also I tried installing these packages but it did not change anything:

```diff
+        "@types/core-js": "^2.5.5",
+        "@types/jasmine": "^4.3.1",
+        "@types/lodash": "^4.14.191",
+        "lodash": "^4.17.21",
```

**Comment by sbishel** [comment]
@wiggin77 - Do you know what might be missing from Fedora?

**Comment by wiggin77** [comment]
@lexoyo can you try `npm install lodash.difference`

**Comment by sbishel** [comment]
@lexoyo - Please reopen if still an issue.
